language: ruby
rvm:
  - 1.9.3
bundler_args: --without local
script: 
  - bundle exec rake spec:ci
before_install:
  - lsb_release -a
  - sudo apt-get install libarchive-dev
before_script:
  - createuser -s adept
  - rake db:create:all
  - rake db:test:prepare
branches:
  only:
    - master