development:
  adapter: postgresql
  encoding: unicode
  database: adept_development
  pool: 5
  username: adept
  password:
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: adept_test
  pool: 5
  username: adept
  password:
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: adept_production
  pool: 5
  username: adept
  password:
  host: localhost
  port: 5432